import bcrypt from "bcryptjs";

const data = {
  users: [
    // text password in database is Insecure => use bcrypt library
    {
      firstName: "Roopali",
      lastName: "Singh",
      address: "XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX",
      city: "Delhi",
      state: "Delhi",
      pin: 110052,
      email: "roopali.singh.222@gmail.com",
      password: bcrypt.hashSync("moon", 8),
      isAdmin: true,
    },
    {
      firstName: "Yash",
      lastName: "Singh",
      email: "yashu@gmail.com",
      address: "YYYYYY YYYYYY YYYYYY YYYYYY YYYYYY YYYYYY YYYYYY",
      city: "Mumbai",
      state: "Maharashtra",
      pin: 110092,
      password: bcrypt.hashSync("doctor", 8),
      isAdmin: false,
    },
    {
      firstName: "Oreo",
      lastName: "Singh",
      email: "oreo@gmail.com",
      address: "OOOOOO OOOOOO OOOOOO OOOOOO OOOOOO OOOOOO OOOOOO",
      city: "Delhi",
      state: "Banglore",
      pin: 110001,
      password: bcrypt.hashSync("dog", 8),
      isAdmin: false,
    },
  ],

  products: [
    // best_sellers=  {
    // category: "Best Sellers",
    // info: [
    {
      // _id: "1",
      category: "Best Sellers",
      name: "One Shoulder Pleated Mania Gown",
      alt: "One Shoulder Pleated Mania Gown",
      image: "../images/dressess/dress6.jpg",
      price: {
        lower: 7499,
        upper: null,
      },
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: {
        color: "blue",
        neckline: "one-shoulder",
        type: "gown",
        fabric: "pleated georgette fabric",
        waist_line: "2 inch belt",
        lining: "present",
      },
    },
    {
      // _id: "2",
      category: "Best Sellers",
      name: "Deep Burgndy Strapy Back Dress",
      alt: "Deep Burgndy Strapy Back Dress",
      image: "../images/dressess/dress4.jpg",
      price: {
        lower: 3299,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "deep burgundy",
        neckline: "mesh in the neckline",
        type: "gown",
        fabric: "polyblend",
        waist_line: "side zipper",
        lining: "absent",
      },
    },
    {
      // _id: "3",
      category: "Best Sellers",
      name: "Mirynee Pink Two Piece Set",
      alt: "Mirynee Pink Two Piece Set",
      image: "../images/dressess/dress3.jpg",
      price: {
        lower: 4200,
        upper: null,
      },
      countInStock: 0,
      rating: 3,
      numReviews: 13,
      description: {
        color: "pink",
        neckline: "mesh in the neckline",
        type: "two piece dress",
        fabric: "polyblend",
        waist_line: "two piece",
        lining: "absent",
      },
    },
    {
      // _id: "4",
      category: "Best Sellers",
      name: "Mirynee Peach Two Piece Set",
      alt: "Mirynee Peach Two Piece Set",
      image: "../images/dressess/dress7.jpg",
      price: {
        lower: 4399,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "peach, black",
        neckline: "semi-deep",
        type: "dress",
        fabric: "polyblend",
        waist_line: "semi-stretchable",
        lining: "present",
      },
    },
    {
      // _id: "5",
      category: "Best Sellers",
      name: "Maroon Multi-Layer Princess Feel Gown",
      alt: "Maroon Multi-Layer Princess Feel Gown",
      image: "../images/dressess/dress8.jpg",
      price: {
        lower: 14100,
        upper: 10100,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "maroon",
        neckline: "halter neck-pattern",
        type: "gown",
        fabric: "mesh",
        lining: "present",
      },
    },
    {
      // _id: "6",
      category: "Best Sellers",
      name: "Off-Shoulder Cinderrella Look Gown",
      alt: "Off-Shoulder Cinderrella Look Gown",
      image: "../images/dressess/dress9.jpg",
      price: {
        lower: 13000,
        upper: 8999,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "blue",
        neckline: "off-shoulder shaped neckline",
        type: "gown",
        fabric: "dutch satin",
        lining: "present",
      },
    },
    {
      // _id: "4",
      category: "Best Sellers",
      name: "Mirynee Peach Two Piece Set",
      alt: "Mirynee Peach Two Piece Set",
      image: "../images/dressess/dress7.jpg",
      price: {
        lower: 4399,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "peach, black",
        neckline: "semi-deep",
        type: "dress",
        fabric: "polyblend",
        waist_line: "semi-stretchable",
        lining: "present",
      },
    },
    {
      // _id: "3",
      category: "Best Sellers",
      name: "Mirynee Pink Two Piece Set",
      alt: "Mirynee Pink Two Piece Set",
      image: "../images/dressess/dress3.jpg",
      price: {
        lower: 4200,
        upper: null,
      },
      countInStock: 0,
      rating: 3,
      numReviews: 13,
      description: {
        color: "pink",
        neckline: "mesh in the neckline",
        type: "two piece dress",
        fabric: "polyblend",
        waist_line: "two piece",
        lining: "absent",
      },
    },
    // ],
    // },

    // new_arrivals: {
    // category: "New Arrivals",
    // info: [
    {
      // _id: "7",
      category: "New Arrivals",
      name: "Pretty Pink Perfect Tube Dress",
      alt: "Pretty Pink Perfect Tube Dress",
      image: "../images/dressess/dress1.jpg",
      price: {
        lower: 4199,
        upper: null,
      },
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: {
        color: "pink",
        neckline: "tube syle",
        type: "dress",
        fabric: "polyblend",
        waist_line: "stretchable",
        lining: "absent",
      },
    },
    {
      // _id: "8",
      category: "New Arrivals",
      name: "Kiara Style It Around Cute Dress",
      alt: "Kiara Style It Around Cute Dress",
      image: "../images/dressess/dress5.jpg",
      price: {
        lower: 4899,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "black & white",
        neckline: "halter neck-pattern",
        type: "dress",
        fabric: "mesh",
        waist_line: "side zipper",
        lining: "present",
      },
    },
    {
      // _id: "9",
      category: "New Arrivals",
      name: "Deep Burgndy Strapy Back Dress",
      alt: "Deep Burgndy Strapy Back Dress",
      image: "../images/dressess/dress4.jpg",
      price: {
        lower: 3299,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "deep burgndy",
        neckline: "mesh in the neckline",
        type: "gown",
        fabric: "polyblend",
        waist_line: "side zipper",
        lining: "absent",
      },
    },
    {
      // _id: "10",
      category: "New Arrivals",
      name: "Black Magic Tube Tulle Dress",
      alt: "Black Magic Tube Tulle Dress",
      image: "../images/dressess/dress2.jpg",
      price: {
        lower: 3499,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "black",
        neckline: "tube-pattern",
        type: "dress",
        fabric: "polyblend + net",
        waist_line: "semi-stretchable",
        lining: "absent",
      },
    },
    {
      // _id: "11",
      category: "New Arrivals",
      name: "One Shoulder Pleated Mania Gown",
      alt: "One Shoulder Pleated Mania Gown",
      image: "../images/dressess/dress1.jpg",
      price: {
        lower: 7499,
        upper: null,
      },
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: {
        color: "blue",
        neckline: "one-shoulder",
        type: "gown",
        fabric: "pleated georgette fabric",
        waist_line: "2 inch belt",
        lining: "present",
      },
    },
    {
      // _id: "12",
      category: "New Arrivals",
      name: "Mirynee Peach Two Piece Set",
      alt: "Mirynee Peach Two Piece Set",
      image: "../images/dressess/dress7.jpg",
      price: {
        lower: 4399,
        upper: null,
      },
      countInStock: 0,
      rating: 3,
      numReviews: 13,
      description: {
        color: "peach, black",
        neckline: "semi-deep",
        type: "dress",
        fabric: "polyblend",
        waist_line: "semi-stretchable",
        lining: "present",
      },
    },
    {
      // _id: "13",
      category: "New Arrivals",
      name: "Maroon Multi-Layer Princess Feel Gown",
      alt: "Maroon Multi-Layer Princess Feel Gown",
      image: "../images/dressess/dress8.jpg",
      price: {
        lower: 14100,
        upper: 10100,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "maroon",
        neckline: "halter neck-pattern",
        type: "gown",
        fabric: "mesh",
        lining: "present",
      },
    },
    {
      // _id: "14",
      category: "New Arrivals",
      name: "Off-Shoulder Cinderrella Look Gown",
      alt: "Off-Shoulder Cinderrella Look Gown",
      image: "../images/dressess/dress9.jpg",
      price: {
        lower: 13000,
        upper: 8999,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "blue",
        neckline: "off-shoulder shaped neckline",
        type: "gown",
        fabric: "dutch satin",
        lining: "present",
      },
    },
    {
      // _id: "12",
      category: "New Arrivals",
      name: "Mirynee Peach Two Piece Set",
      alt: "Mirynee Peach Two Piece Set",
      image: "../images/dressess/dress7.jpg",
      price: {
        lower: 4399,
        upper: null,
      },
      countInStock: 0,
      rating: 3,
      numReviews: 13,
      description: {
        color: "peach, black",
        neckline: "semi-deep",
        type: "dress",
        fabric: "polyblend",
        waist_line: "semi-stretchable",
        lining: "present",
      },
    },
    {
      // _id: "10",
      category: "New Arrivals",
      name: "Black Magic Tube Tulle Dress",
      alt: "Black Magic Tube Tulle Dress",
      image: "../images/dressess/dress2.jpg",
      price: {
        lower: 3499,
        upper: null,
      },
      countInStock: 10,
      rating: 3,
      numReviews: 13,
      description: {
        color: "black",
        neckline: "tube-pattern",
        type: "dress",
        fabric: "polyblend + net",
        waist_line: "semi-stretchable",
        lining: "absent",
      },
    },
    // ],
    // },
  ],
};

export default data;
